name: Fetch Hokkaido News

on:
  schedule:
    - cron: '10 21 * * *' # JST 06:10 (UTC-9h)
    - cron: '10 9 * * *'  # JST 18:10 (UTC-9h)
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run fetch script
        run: node scripts/fetch_hokkaido_news.mjs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/news/hokkaido.json
          git add public/news/sankei.json
          git add public/news/nhk.json
          git add public/news/asahi.json
          git add public/news/akt-yahoo.json
          git add public/news/iwatenpv-yahoo.json
          git add public/news/all.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(news): update hokkaido.json"
            git push
          fi


